### ISSUE TITLE
default tag

### ISSUE THREAD

**Issue by iofjuupasli** [af/JSnoX#10]
The most frequently used tag is `div`.

```js
d('.my-class')
```
same as
```js
d('div.my-class')
```

So can `div` be default tag if another is not provided?

**Comment by af** [comment]
I don't necessarily like the tagName being implicit, but I suppose it is a completely optional feature (and should be easy to add). Some folks are probably used to this from jade (and other templating systems) as well. I'll take a look at adding this sometime in the next week. Thanks for the suggestion!
