### ISSUE TITLE
Element: `ref` is not a prop (react@15)

### ISSUE THREAD

**Issue by larsthorup** [af/JSnoX#14]
Using jsnox@2.1.2 with react@15 I get this warning:

    Warning: Element: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)
    warning @ warning.js:44
    Object.defineProperty.get @ ReactElement.js:188
    jsnoxClient @ jsnox.js:119

Do we need this check at all (line 119: typeof props.ref !== 'undefined') or is there a way to work around this new constraint in React?

**Comment by af** [comment]
@larsthorup Thanks, I haven't upgraded to v15 yet so I hadn't seen this. The line in question is trying to sniff whether one of the arguments is a ReactElement. There should be another way to detect this, I'll try and sort it out this weekend if nobody beats me to it!

**Comment by af** [comment]
Hi @larsthorup could you try latest `master` and see if the warning still happens for you?

**Comment by larsthorup** [comment]
@af Yes this works, and the warning is gone. Thx!

**Comment by af** [comment]
Thanks, just pushed out v2.1.3 so you can install it via npm if needed

**Comment by larsthorup** [comment]
Thanks!
